name: CI

on: [push]

jobs: 
  build-and-test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app

      - name: Build and test
        run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "EssentialFeed" -destination "platform=iOS Simulator,name=iPhone 11" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

